# deployment.yaml
# created based on https://docs.n8n.io/hosting/installation/docker/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: nocode
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
        version: "1.73.1" 
    spec:
      containers:
      - name: n8n-container
        image: docker.n8n.io/n8nio/n8n:1.73.1
        ports:
        - containerPort: 5678
        envFrom:
          - configMapRef:
              name: n8n-config # Reference to the ConfigMap for non-sensitive configurations
        env:
          - name: DB_TYPE
            valueFrom:
              configMapKeyRef:
                name: n8n-config # Pulling DB_TYPE from ConfigMap
                key: DB_TYPE

          - name: DB_POSTGRESDB_DATABASE
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: DB_POSTGRESDB_DATABASE
          - name: DB_POSTGRESDB_HOST
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: DB_POSTGRESDB_HOST
          - name: DB_POSTGRESDB_PORT
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: DB_POSTGRESDB_PORT
          - name: DB_POSTGRESDB_USER
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: DB_POSTGRESDB_USER
          - name: DB_POSTGRESDB_SCHEMA
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: DB_POSTGRESDB_SCHEMA
          - name: DB_POSTGRESDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: DB_POSTGRESDB_PASSWORD
