# secret.yaml
# created based on https://docs.n8n.io/hosting/installation/docker/
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: nocode
type: Opaque
data:
  DB_POSTGRESDB_DATABASE: 
  DB_POSTGRESDB_HOST: 
  DB_POSTGRESDB_PORT: 
  DB_POSTGRESDB_USER: 
  DB_POSTGRESDB_SCHEMA: 
  DB_POSTGRESDB_PASSWORD: 
